# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reportesDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reportes(object):
    def setupUi(self, reportes):
        reportes.setObjectName("reportes")
        reportes.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\GLAM_MAKEUP_STORE\GUI\images\store_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        reportes.setWindowIcon(icon)
        self.HeadContainer = QtWidgets.QGroupBox(reportes)
        self.HeadContainer.setEnabled(True)
        self.HeadContainer.setGeometry(QtCore.QRect(10, 10, 191, 71))
        self.HeadContainer.setTitle("")
        self.HeadContainer.setObjectName("HeadContainer")
        self.logo = QtWidgets.QLabel(self.HeadContainer)
        self.logo.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\GLAM_MAKEUP_STORE\GUI\images\store_logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.Reportes = QtWidgets.QLabel(self.HeadContainer)
        self.Reportes.setGeometry(QtCore.QRect(70, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.Reportes.setFont(font)
        self.Reportes.setObjectName("Reportes")
        self.container = QtWidgets.QFrame(reportes)
        self.container.setGeometry(QtCore.QRect(210, 180, 381, 241))
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.inventario = QtWidgets.QPushButton(self.container)
        self.inventario.setGeometry(QtCore.QRect(10, 20, 111, 61))
        self.inventario.setObjectName("inventario")
        self.ventas = QtWidgets.QPushButton(self.container)
        self.ventas.setGeometry(QtCore.QRect(260, 160, 111, 61))
        self.ventas.setObjectName("ventas")

        self.retranslateUi(reportes)
        QtCore.QMetaObject.connectSlotsByName(reportes)

    def retranslateUi(self, reportes):
        _translate = QtCore.QCoreApplication.translate
        reportes.setWindowTitle(_translate("reportes", "Reportes"))
        self.Reportes.setText(_translate("reportes", "Reportes"))
        self.inventario.setText(_translate("reportes", "Inventario"))
        self.ventas.setText(_translate("reportes", "Ventas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reportes = QtWidgets.QWidget()
    ui = Ui_reportes()
    ui.setupUi(reportes)
    reportes.show()
    sys.exit(app.exec_())
