# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inventario/inventarioPanelDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inventario(object):
    def setupUi(self, Inventario):
        Inventario.setObjectName("Inventario")
        Inventario.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\GLAM_MAKEUP_STORE\GUI\images\store_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Inventario.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Inventario)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 201, 71))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.logo = QtWidgets.QLabel(self.groupBox)
        self.logo.setGeometry(QtCore.QRect(10, 10, 50, 50))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("C:\GLAM_MAKEUP_STORE\GUI\images\store_logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.Reportes = QtWidgets.QLabel(self.groupBox)
        self.Reportes.setGeometry(QtCore.QRect(70, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(False)
        self.Reportes.setFont(font)
        self.Reportes.setObjectName("Reportes")
        self.container = QtWidgets.QFrame(Inventario)
        self.container.setGeometry(QtCore.QRect(210, 180, 381, 241))
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.productos = QtWidgets.QPushButton(self.container)
        self.productos.setGeometry(QtCore.QRect(260, 10, 111, 61))
        self.productos.setObjectName("productos")
        self.servicios = QtWidgets.QPushButton(self.container)
        self.servicios.setGeometry(QtCore.QRect(10, 170, 111, 61))
        self.servicios.setObjectName("servicios")

        self.retranslateUi(Inventario)
        QtCore.QMetaObject.connectSlotsByName(Inventario)

    def retranslateUi(self, Inventario):
        _translate = QtCore.QCoreApplication.translate
        Inventario.setWindowTitle(_translate("Inventario", "Inventario"))
        self.Reportes.setText(_translate("Inventario", "Inventario"))
        self.productos.setText(_translate("Inventario", "Productos"))
        self.servicios.setText(_translate("Inventario", "Servicios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Inventario = QtWidgets.QWidget()
    ui = Ui_Inventario()
    ui.setupUi(Inventario)
    Inventario.show()
    sys.exit(app.exec_())
